ec_propietario_homepage:
    pattern:  /
    defaults: { _controller: ECPropietarioBundle:Default:index }
    
ec_propietario_perfil:
    pattern:  /perfil
    defaults: { _controller: ECPropietarioBundle:Default:modificacion_perfil }
    
ec_propietario_contraseña:
    pattern:  /contraseña
    defaults: { _controller: ECPropietarioBundle:Default:modificacion_contraseña }