#FRONTEND
ec_principal_homepage:
    pattern:  /
    defaults: { _controller: ECPrincipalBundle:Default:index}
    
ec_principal_check:
    pattern:  /check
    defaults: { _controller: ECPrincipalBundle:Default:check}
    
ec_principal_eres_adminfincas:
    pattern:  /adfincas
    defaults: { _controller: ECPrincipalBundle:Default:eres_adminfincas}
    
ec_principal_contacto:
    pattern:  /contacto
    defaults: { _controller: ECPrincipalBundle:Default:contacto}
    
select_cities:
   pattern:  /cities
   defaults: { _controller: ECPrincipalBundle:Default:cities}

select_provinces:
   pattern:  /provinces
   defaults: { _controller: ECPrincipalBundle:Default:provinces}
   
#ANUNCIOS
ec_listado_anuncios:
   pattern: /anuncios/listado
   defaults: { _controller: ECPrincipalBundle:Anuncio:listado }

#COMUNIDAD
ec_adminfincas_alta_comunidad:
    pattern:  /adminfincas/alta/comunidad
    defaults: { _controller: ECPrincipalBundle:Comunidad:alta_comunidad }
    
ec_adminfincas_comunidad_editar:
    pattern:  /adminfincas/comunidad/{cif}/editar
    defaults: { _controller: ECPrincipalBundle:Comunidad:editar_comunidad }
    
ec_adminfincas_comunidad_eliminar:
    pattern:  /adminfincas/comunidad/{cif}/eliminar
    defaults: { _controller: ECPrincipalBundle:Comunidad:eliminar_comunidad }

ec_adminfincas_listado_comunidades:
    pattern:  /adminfincas/listado/comunidades
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades }
    
ec_adminfincas_listado_comunidades_pdf:
    pattern:  /adminfincas/listado/comunidades/pdf
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_listado_comunidades_csv:
    pattern: /adminfincas/listado/comunidades/csv
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades_csv }
    
ec_tablon_comunidad:
    pattern:  /comunidad/tablon/{cif}
    defaults: { _controller: ECPrincipalBundle:Comunidad:ver_tablon_comunidad, cif: null }
    
ec_adminfincas_estadisticas_comunidades:
   pattern:  /adminfincas/estadisticas/comunidades
   defaults: { _controller: ECPrincipalBundle:Comunidad:estadisticasComunidades }

#REUNIONES
ec_ver_reunion_comunidad:
    pattern:  /comunidad/reunion/{id}/{cif}
    defaults: { _controller: ECPrincipalBundle:Reunion:ver_reunion_comunidad, cif: null }
    options:
        expose: true
    
ec_reuniones_comunidad:
    pattern:  /comunidad/reuniones/{cif}
    defaults: { _controller: ECPrincipalBundle:Reunion:ver_reuniones_comunidad, cif: null }
    
ec_reunion_descargar:
    pattern:  /reunion/descargar/{id}
    defaults: { _controller: ECPrincipalBundle:Reunion:descargar_documento_reunion }

ec_adminfincas_eliminar_reunion:
    pattern:  /adminfincas/comunidad/{cif}/eliminar/reunion/{id}
    defaults: { _controller: ECPrincipalBundle:Reunion:eliminar_reunion }
   
#BLOQUES
ec_adminfincas_comunidad_listado_bloques:
    pattern:  /adminfincas/comunidad/{cif}/listado/bloques
    defaults: { _controller: ECPrincipalBundle:Bloque:comunidad_listado_bloques }
    
ec_adminfincas_comunidad_listado_bloques_pdf:
    pattern:  /adminfincas/comunidad/{cif}/listado/bloques/pdf
    defaults: { _controller: ECPrincipalBundle:Bloque:comunidad_listado_bloques_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_bloques_csv:
    pattern: /adminfincas/comunidad/{cif}/listado/bloques/csv
    defaults: { _controller: ECPrincipalBundle:Bloque:comunidad_listado_bloques_csv }
    
ec_adminfincas_comunidad_alta_bloque:
    pattern:  /adminfincas/comunidad/{cif}/alta/bloque
    defaults: { _controller: ECPrincipalBundle:Bloque:comunidad_alta_bloque }
    
ec_adminfincas_comunidad_eliminar_bloque:
    pattern:  /adminfincas/comunidad/{cif}/bloque/eliminar/{num}
    defaults: { _controller: ECPrincipalBundle:Bloque:comunidad_eliminar_bloque }
    
#DOCUMENTOS
ec_adminfincas_comunidad_documento_upload:
    pattern:  /adminfincas/comunidad/{cif}/documento/upload
    defaults: { _controller: ECPrincipalBundle:Documento:upload }
    
ec_listado_documentos:
    pattern:  /documentos/listado/{cif}
    defaults: { _controller: ECPrincipalBundle:Documento:listado, cif: null }
    
ec_adminfincas_comunidad_eliminar_documento:
    pattern:  /adminfincas/comunidad/{cif}/documento/eliminar/{id}
    defaults: { _controller: ECPrincipalBundle:Documento:eliminar }
    
ec_documento_descargar:
    pattern:  /documento/descargar/{id}
    defaults: { _controller: ECPrincipalBundle:Documento:descargar }
    
ec_documento_previsualizar:
    pattern:  /documento/previsualizar/{id}/{cif}
    defaults: { _controller: ECPrincipalBundle:Documento:previsualizar, cif: null }
    
#USUARIO
ec_usuario_contraseña:
    pattern:  /usuario/contraseña
    defaults: { _controller: ECPrincipalBundle:Usuario:modificacion_contraseña }

#PROPIETARIOS
ec_adminfincas_comunidad_alta_propietario:
    pattern:  /adminfincas/comunidad/{cif}/alta/propietario/{_format}
    defaults: { _controller: ECPrincipalBundle:Propietario:alta_propietario, _format: html }
    requirements:
      _format: pdf|html
    
ec_adminfincas_comunidad_generar_password_propietario:
    pattern:  /adminfincas/comunidad/{cif}/propietario/password/{id}
    defaults: { _controller: ECPrincipalBundle:Propietario:comunidad_generar_password_propietario_pdf, _format:pdf }
    requirements:
      _format: pdf
    
ec_adminfincas_comunidad_listado_propietarios:
    pattern:  /adminfincas/comunidad/{cif}/listado/propietarios
    defaults: { _controller: ECPrincipalBundle:Propietario:comunidad_listado_propietarios }
    
ec_adminfincas_comunidad_listado_propietarios_pdf:
    pattern:  /adminfincas/comunidad/{cif}/listado/propietarios/pdf
    defaults: { _controller: ECPrincipalBundle:Propietario:comunidad_listado_propietarios_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_propietarios_csv:
    pattern: /adminfincas/comunidad/{cif}/listado/propietarios/csv
    defaults: { _controller: ECPrincipalBundle:Propietario:comunidad_listado_propietarios_csv }
    
ec_adminfincas_comunidad_eliminar_propietario:
    pattern:  /adminfincas/comunidad/{cif}/propietario/eliminar/{id}
    defaults: { _controller: ECPrincipalBundle:Propietario:comunidad_eliminar_propietario } 
    
ec_propietario_perfil:
    pattern:  /propietario/perfil
    defaults: { _controller: ECPrincipalBundle:Propietario:modificacion_perfil }
    
#INCIDENCIAS
ec_propietario_nueva_incidencia:
    pattern:  /propietario/incidencia/nueva
    defaults: { _controller: ECPrincipalBundle:Incidencia:nueva_incidencia }
    
ec_listado_incidencias:
    pattern:  /incidencias/listado/{cif}
    defaults: { _controller: ECPrincipalBundle:Incidencia:listado_incidencias, cif: null }
    
ec_incidencia:
    pattern:  /incidencia/{id}
    defaults: { _controller: ECPrincipalBundle:Incidencia:ver_incidencia }
    
ec_adminfincas_estadisticas_incidencias_categorias:
   pattern:  /adminfincas/estadisticas/incidencias/categorias
   defaults: { _controller: ECPrincipalBundle:Incidencia:estadisticasIncidenciasCategorias }
   
ec_adminfincas_estadisticas_incidencias_fecha:
   pattern:  /adminfincas/estadisticas/incidencias/fecha
   defaults: { _controller: ECPrincipalBundle:Incidencia:estadisticasIncidenciasFecha }
    
#ROLE   
ec_adminfincas_nombrar_presidente:
    pattern:  /adminfincas/comunidad/{cif}/nombrarpresidente/{id}
    defaults: { _controller: ECPrincipalBundle:Role:nombrar_presidente }

ec_adminfincas_nombrar_vicepresidente:
    pattern:  /adminfincas/comunidad/{cif}/nombrarvicepresidente/{id}
    defaults: { _controller: ECPrincipalBundle:Role:nombrar_vicepresidente }

#ADMINFINCAS
ec_principal_alta_adminfincas:
    pattern:  /alta
    defaults: { _controller: ECPrincipalBundle:AdminFincas:alta_adminfincas}

ec_adminfincas_perfil:
    pattern:  /adminfincas/perfil
    defaults: { _controller: ECPrincipalBundle:AdminFincas:modificacion_perfil }