#FRONTEND
ec_principal_eres_adminfincas:
    pattern:  /adfincas
    defaults: { _controller: ECPrincipalBundle:Default:eres_adminfincas}
    
ec_principal_contacto:
    pattern:  /contacto
    defaults: { _controller: ECPrincipalBundle:Default:contacto}
    
select_cities:
   pattern:  /cities
   defaults: { _controller: ECPrincipalBundle:Default:cities}

select_provinces:
   pattern:  /provinces
   defaults: { _controller: ECPrincipalBundle:Default:provinces}
   
#ANUNCIOS
ec_buscador_contactar:
    pattern:  /contactar
    defaults: { _controller: ECPrincipalBundle:Anuncio:contactar}
    requirements:
        _method:  POST
    options:
        expose: true
        
ec_buscador_denunciar:
    pattern:  /denunciar
    defaults: { _controller: ECPrincipalBundle:Anuncio:denunciar}
    requirements:
        _method:  POST
    options:
        expose: true
    
ec_nuevo_anuncio:
   pattern: /nuevo/anuncio/{id_comunidad}
   defaults: { _controller: ECPrincipalBundle:Anuncio:nuevo_anuncio, id_comunidad: null }
   
ec_listado_mis_anuncios:
   pattern: /anuncios/listado/{id_comunidad}
   defaults: { _controller: ECPrincipalBundle:Anuncio:listado_mis_anuncios, id_comunidad: null }
   
ec_modificar_anuncio:
   pattern: /modificar/anuncio/{id}
   defaults: { _controller: ECPrincipalBundle:Anuncio:modificar }
   
ec_modificar_anuncio_imagenes:
   pattern: /modificar/anuncio/imagenes/{id}
   defaults: { _controller: ECPrincipalBundle:Anuncio:modificarImagenes }
   
ec_modificar_anuncio_orden_imagenes_ajax:
   pattern: /modificar/anuncio/orden/imagenes
   defaults: { _controller: ECPrincipalBundle:Anuncio:modificarImagenesOrden }
   
ec_eliminar_imagen_anuncio:
   pattern: /eliminar/imagen/{id_imagen}/anuncio/{id}
   defaults: { _controller: ECPrincipalBundle:Anuncio:eliminarImagenAnuncio }
   
ec_eliminar_anuncio:
   pattern: /eliminar/anuncio/{id}
   defaults: { _controller: ECPrincipalBundle:Anuncio:Eliminar }
   
ec_adminfincas_estadisticas_anuncios_categorias:
   pattern:  /adminfincas/estadisticas/anuncios/categorias
   defaults: { _controller: ECPrincipalBundle:Anuncio:estadisticasAnunciosCategorias }

#COMUNIDAD
ec_adminfincas_alta_comunidad:
    pattern:  /adminfincas/alta/comunidad
    defaults: { _controller: ECPrincipalBundle:Comunidad:alta_comunidad }
    
ec_adminfincas_comunidad_editar:
    pattern:  /adminfincas/comunidad/{id_comunidad}/editar
    defaults: { _controller: ECPrincipalBundle:Comunidad:editar_comunidad }
    
ec_adminfincas_comunidad_eliminar:
    pattern:  /adminfincas/comunidad/{id_comunidad}/eliminar
    defaults: { _controller: ECPrincipalBundle:Comunidad:eliminar_comunidad }

ec_adminfincas_listado_comunidades:
    pattern:  /adminfincas/listado/comunidades
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades }
    
ec_adminfincas_listado_comunidades_pdf:
    pattern:  /adminfincas/listado/comunidades/pdf
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_listado_comunidades_csv:
    pattern: /adminfincas/listado/comunidades/csv
    defaults: { _controller: ECPrincipalBundle:Comunidad:listado_comunidades_csv }
    
ec_tablon_comunidad:
    pattern:  /comunidad/tablon/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Comunidad:ver_tablon_comunidad, id_comunidad: null }
    
ec_adminfincas_estadisticas_comunidades:
   pattern:  /adminfincas/estadisticas/comunidades
   defaults: { _controller: ECPrincipalBundle:Comunidad:estadisticasComunidades }

#REUNIONES
ec_ver_reunion_comunidad:
    pattern:  /comunidad/reunion/{id}/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Reunion:ver_reunion, id_comunidad: null }
    options:
        expose: true
    
ec_reuniones_comunidad:
    pattern:  /comunidad/reuniones/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Reunion:ver_reuniones, id_comunidad: null }
    
ec_reunion_descargar:
    pattern:  /reunion/descargar/{id}
    defaults: { _controller: ECPrincipalBundle:Reunion:descargar_documento_reunion }

ec_adminfincas_eliminar_reunion:
    pattern:  /adminfincas/comunidad/{id_comunidad}/eliminar/reunion/{id}
    defaults: { _controller: ECPrincipalBundle:Reunion:eliminar_reunion }
   
#BLOQUES
ec_adminfincas_comunidad_listado_bloques:
    pattern:  /adminfincas/comunidad/{id_comunidad}/listado/bloques
    defaults: { _controller: ECPrincipalBundle:Bloque:listado_bloques }
    
ec_adminfincas_comunidad_listado_bloques_pdf:
    pattern:  /adminfincas/comunidad/{id_comunidad}/listado/bloques/pdf
    defaults: { _controller: ECPrincipalBundle:Bloque:listado_bloques_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_bloques_csv:
    pattern: /adminfincas/comunidad/{id_comunidad}/listado/bloques/csv
    defaults: { _controller: ECPrincipalBundle:Bloque:listado_bloques_csv }
    
ec_adminfincas_comunidad_alta_bloque:
    pattern:  /adminfincas/comunidad/{id_comunidad}/alta/bloque
    defaults: { _controller: ECPrincipalBundle:Bloque:alta_bloque }
    
ec_adminfincas_comunidad_editar_bloque:
    pattern:  /adminfincas/comunidad/{id_comunidad}/bloque/editar/{num}
    defaults: { _controller: ECPrincipalBundle:Bloque:editar_bloque }
    
ec_adminfincas_comunidad_eliminar_bloque:
    pattern:  /adminfincas/comunidad/{id_comunidad}/bloque/eliminar/{num}
    defaults: { _controller: ECPrincipalBundle:Bloque:eliminar_bloque }
    
#DOCUMENTOS
ec_adminfincas_comunidad_documento_upload:
    pattern:  /adminfincas/comunidad/{id_comunidad}/documento/upload
    defaults: { _controller: ECPrincipalBundle:Documento:upload }
    
ec_listado_documentos:
    pattern:  /documentos/listado/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Documento:listado, id_comunidad: null }
    
ec_adminfincas_comunidad_eliminar_documento:
    pattern:  /adminfincas/comunidad/{id_comunidad}/documento/eliminar/{id}
    defaults: { _controller: ECPrincipalBundle:Documento:eliminar }
    
ec_adminfincas_comunidad_consultas_documento:
    pattern:  /adminfincas/documento/consultas/{id}/pdf
    defaults: { _controller: ECPrincipalBundle:Documento:consultas, _format:pdf }
    
ec_documento_descargar:
    pattern:  /documento/descargar/{id}
    defaults: { _controller: ECPrincipalBundle:Documento:descargar }
    
ec_documento_previsualizar:
    pattern:  /documento/previsualizar/{id}/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Documento:previsualizar, id_comunidad: null }
    
#USUARIO
ec_usuario_contraseña:
    pattern:  /usuario/contraseña
    defaults: { _controller: ECPrincipalBundle:Usuario:modificacion_contraseña }

#PROPIETARIOS
ec_adminfincas_comunidad_alta_propietario:
    pattern:  /adminfincas/comunidad/{id_comunidad}/alta/propietario/{_format}
    defaults: { _controller: ECPrincipalBundle:Propietario:alta_propietario, _format: html }
    requirements:
      _format: pdf|html
    
ec_adminfincas_comunidad_generar_password_propietario:
    pattern:  /adminfincas/comunidad/{id_comunidad}/propietario/password/{id}
    defaults: { _controller: ECPrincipalBundle:Propietario:generar_password_propietario_pdf, _format:pdf }
    requirements:
      _format: pdf
    
ec_adminfincas_comunidad_listado_propietarios:
    pattern:  /adminfincas/comunidad/{id_comunidad}/listado/propietarios
    defaults: { _controller: ECPrincipalBundle:Propietario:listado_propietarios }
    
ec_adminfincas_comunidad_listado_propietarios_pdf:
    pattern:  /adminfincas/comunidad/{id_comunidad}/listado/propietarios/pdf
    defaults: { _controller: ECPrincipalBundle:Propietario:listado_propietarios_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_propietarios_csv:
    pattern: /adminfincas/comunidad/{id_comunidad}/listado/propietarios/csv
    defaults: { _controller: ECPrincipalBundle:Propietario:listado_propietarios_csv }
    
ec_adminfincas_comunidad_eliminar_propietario:
    pattern:  /adminfincas/comunidad/{id_comunidad}/propietario/eliminar/{id}
    defaults: { _controller: ECPrincipalBundle:Propietario:eliminar_propietario } 
    
ec_propietario_perfil:
    pattern:  /propietario/perfil
    defaults: { _controller: ECPrincipalBundle:Propietario:modificacion_perfil }
    
#INCIDENCIAS
ec_propietario_nueva_incidencia:
    pattern:  /propietario/incidencia/nueva
    defaults: { _controller: ECPrincipalBundle:Incidencia:nueva_incidencia }
    
ec_listado_incidencias:
    pattern:  /incidencias/listado/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Incidencia:listado_incidencias, id_comunidad: null }
    
ec_listado_incidencias_pdf:
    pattern:  /incidencias/listado/{id_comunidad}/pdf
    defaults: { _controller: ECPrincipalBundle:Incidencia:listado_incidencias_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_listado_incidencias_csv:
    pattern: /incidencias/listado/{id_comunidad}/csv
    defaults: { _controller: ECPrincipalBundle:Incidencia:listado_incidencias_csv }
    
ec_incidencia:
    pattern:  /incidencia/{id}
    defaults: { _controller: ECPrincipalBundle:Incidencia:ver_incidencia }
    
ec_adminfincas_estadisticas_incidencias_categorias:
   pattern:  /adminfincas/estadisticas/incidencias/categorias
   defaults: { _controller: ECPrincipalBundle:Incidencia:estadisticasIncidenciasCategorias }
   
ec_adminfincas_estadisticas_incidencias_fecha:
   pattern:  /adminfincas/estadisticas/incidencias/fecha
   defaults: { _controller: ECPrincipalBundle:Incidencia:estadisticasIncidenciasFecha }
   
#SERVICIOS
ec_listado_servicios:
   pattern: /comunidad/servicios/listado/{id_comunidad}
   defaults: { _controller: ECPrincipalBundle:Servicio:listado, id_comunidad: null }
   
ec_listado_servicios_pdf:
    pattern:  /comunidad/servicios/listado/pdf/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Servicio:listado_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_listado_servicios_csv:
    pattern: /comunidad/servicios/listado/csv/{id_comunidad}
    defaults: { _controller: ECPrincipalBundle:Servicio:listado_csv }
   
ec_adminfincas_nuevo_servicio:
   pattern: /adminfincas/comunidad/{id_comunidad}/servicios/nuevo
   defaults: { _controller: ECPrincipalBundle:Servicio:nuevo }
   
ec_adminfincas_buscador_servicios:
   pattern: /adminfincas/comunidad/{id_comunidad}/servicios/buscador
   defaults: { _controller: ECPrincipalBundle:Servicio:buscador }
   
ec_adminfincas_ver_servicio:
   pattern: /adminfincas/comunidad/{id_comunidad}/servicios/{id_servicio}
   defaults: { _controller: ECPrincipalBundle:Servicio:ver }
   
ec_adminfincas_añadir_servicio:
   pattern: /adminfincas/comunidad/{id_comunidad}/servicios/añadir/{id_servicio}
   defaults: { _controller: ECPrincipalBundle:Servicio:añadir }
   
ec_adminfincas_quitar_servicio:
   pattern: /adminfincas/comunidad/{id_comunidad}/servicios/quitar/{id_servicio}
   defaults: { _controller: ECPrincipalBundle:Servicio:quitar }
   
ec_adminfincas_comprobar_servicio:
    pattern:  /adminfincas/comprobar/servicio
    defaults: { _controller: ECPrincipalBundle:Servicio:comprobar}
    requirements:
        _method:  POST
    options:
        expose: true
    
#ROLE   
ec_adminfincas_nombrar_presidente:
    pattern:  /adminfincas/comunidad/{id_comunidad}/nombrarpresidente/{id}
    defaults: { _controller: ECPrincipalBundle:Role:nombrar_presidente }

ec_adminfincas_nombrar_vicepresidente:
    pattern:  /adminfincas/comunidad/{id_comunidad}/nombrarvicepresidente/{id}
    defaults: { _controller: ECPrincipalBundle:Role:nombrar_vicepresidente }

#ADMINFINCAS
ec_principal_alta_adminfincas:
    pattern:  /alta
    defaults: { _controller: ECPrincipalBundle:AdminFincas:alta_adminfincas}

ec_adminfincas_baja:
    pattern:  /adminfincas/baja
    defaults: { _controller: ECPrincipalBundle:AdminFincas:baja_adminfincas }
    
ec_adminfincas_perfil:
    pattern:  /adminfincas/perfil
    defaults: { _controller: ECPrincipalBundle:AdminFincas:modificacion_perfil }
    
ec_principal_olvido_password:
    pattern:  /olvido/password
    defaults: { _controller: ECPrincipalBundle:Usuario:olvido_password}