parameters:
#    ec_principal.example.class: EC\PrincipalBundle\Example

services:
    my_listener:
        class: "EC\PrincipalBundle\Listener\LocaleListener"
        arguments: [%locale%]
        tags:
            -  { name: kernel.event_subscriber }

services:
#    ec_principal.example:
#        class: %ec_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
