parameters:
#    ec_principal.example.class: EC\PrincipalBundle\Example

services:
#    ec_principal.example:
#        class: %ec_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
