fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: snowball
                                language: Spanish
                                stopwords: [a, o, u, y, de, en, el, la, los, un, una, uno, se, para, por, sin, tras, hasta, hacia, entre, con, desde]
            types:
                anuncio:
                    mappings:
                        titulo: { type: string, analyzer: my_analyzer}
                        descripcion: { type: string, analyzer: my_analyzer}
                        fecha:
                            type: date
                        precio:
                            type: integer
                        categoria:
                            type: object
                            properties:
                                id:
                                    type: integer
                                nombre: {type:string}
                        comunidad:
                             type: object
                             properties:
                                 city:
                                     type: object
                                     properties:
                                         province:
                                             type: object
                                             properties:
                                                id: {type:integer}
                                                name: {type:string}
                                         name: {type:string}
                        usuario:
                              type: object
                              properties:
                                   telefono: {type:string}
                    persistence:
                        driver: orm
                        model: EC\PrincipalBundle\Entity\Anuncio
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                servicio:
                    mappings:
                        nombre: { type: string, analyzer: my_analyzer}
                        cif:
                           type: string
                        direccion:
                           type: string
                        telefono:
                           type: string
                        categoria:
                            type: object
                            properties:
                                id:
                                    type: integer
                                nombre: {type:string}
                        city:
                            type: object
                            properties:
                                province:
                                    type: object
                                    properties:
                                          id: {type:integer}  
                                          name: {type:string}
                                name: {type:string}
                    persistence:
                        driver: orm
                        model: EC\PrincipalBundle\Entity\Servicio
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true