fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: snowball
                                language: Spanish
            types:
                anuncio:
                    mappings:
                        titulo: { type: string, analyzer: my_analyzer}
                        descripcion: { type: string, analyzer: my_analyzer}
                        fecha:
                            type: date
                        precio:
                            type: integer
                        categoria:
                            type: object
                            properties:
                                id:
                                    type: integer
                                nombre: {type:string}
                        comunidad:
                             type: object
                             properties:
                                 city:
                                     type: object
                                     properties:
                                         province:
                                             type: object
                                             properties:
                                                id: ~  
                                                name: {type:string}
                                         name: {type:string} 
                    persistence:
                        driver: orm
                        model: EC\PrincipalBundle\Entity\Anuncio
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true