home:
    pattern:  /{_locale}
    defaults: { _controller: ECPrincipalBundle:Default:index, _locale:es }

ec_principal:
    resource: "@ECPrincipalBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    defaults: { _locale:es }
    requirements:
        _locale: en|es

login:
   pattern: /{_locale}/login
   defaults: { _controller:ECPrincipalBundle:Default:login, _locale:es }
   requirements:
        _locale: en|es

login_check:
   pattern: /{_locale}/login_check
   defaults: { _locale: es }
   requirements:
        _locale: en|es

logout:
   pattern: /{_locale}/logout
   defaults: { _locale: es }
   requirements:
        _locale: en|es
        
fos_js_routing:
   resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"