security:
    firewalls: 
         privado:
            pattern:    ^/*
            anonymous: ~
            provider: usuarios
            form_login:
               login_path: login
               check_path: login_check
               default_target_path: ec_tablon_comunidad
            logout:
               path: logout
               target: ec_buscador_anuncios
            remember_me:
               key:     "%secret%"
               lifetime: 31536000
               path:     /
               domain:   ~   
    
    role_hierarchy:
        ROLE_PRESIDENTE: ROLE_VECINO
        ROLE_VICEPRESIDENTE: ROLE_VECINO
           
    access_control:
        - { path: ^/.*/root, roles: ROLE_ADMIN }
        - { path: ^/.*/adminfincas/.*, roles: ROLE_ADMINFINCAS }
        - { path: ^/.*/propietario/.*, roles: ROLE_VECINO }
        - { path: ^/.*/usuario/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/incidencia/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/incidencias/listado/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/documento/descargar/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/documento/previsualizar/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/documentos/listado/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/tablon, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/tablon/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/reunion/descargar/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/reunion/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/reuniones/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/anuncio/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/anuncios/listado, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/anuncios/listado/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/servicios/listado, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }
        - { path: ^/.*/servicios/listado/.*, roles: [ROLE_ADMINFINCAS, ROLE_VECINO] }

    providers:
        usuarios:
            entity: { class: EC\PrincipalBundle\Entity\Usuario, property: user }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        EC\PrincipalBundle\Entity\Usuario:
              algorithm:  sha512
              iterations: 10
              encode_as_base64: false