security:
    firewalls: 
         admin:
            pattern:    ^/root
            http_basic:	~
            provider: administradores
            logout:
               path:		/root/logout
               target:	/ 
         frontend:
            pattern:    ^/*
            anonymous: ~
            provider: usuarios
            form_login:
               login_path: login
               check_path: login_check
               default_target_path: ec_principal_homepage
            logout:
               path: logout
               target: ec_principal_homepage     
               
    access_control:
        - { path: ^/root, roles: ROLE_ADMIN }
        - { path: ^/adminfincas, roles: ROLE_ADMINFINCAS }
        - { path: ^/vecino, roles: ROLE_VECINO }

    providers:
        administradores:
            memory:
                users:
                    root: { password: rootpass, roles: 'ROLE_ADMIN' }
        usuarios:
            chain:
                providers: [adminfincas, vecinos]
        adminfincas:
            entity: { class: EC\AdminFincasBundle\Entity\AdminFincas, property: n_colegiado }
        vecinos:
            entity: { class: EC\VecinoBundle\Entity\Vecino, property: dni }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        EC\AdminFincasBundle\Entity\AdminFincas:
              algorithm:  sha512
              iterations: 10
              encode_as_base64: false
        EC\VecinoBundle\Entity\Vecino:
              algorithm:  sha512
              iterations: 10
              encode_as_base64: false