security:
    firewalls: 
         admin:
            pattern:    ^/root
            http_basic:	~
            provider: administradores
            logout:
               path:		/root/logout
               target:	/
         privado:
            pattern:    ^/*
            anonymous: ~
            provider: usuarios
            form_login:
               login_path: login
               check_path: login_check
               default_target_path: ec_principal_check
            logout:
               path: logout
               target: ec_principal_homepage     
    
    role_hierarchy:
        ROLE_PRESIDENTE: ROLE_VECINO
        ROLE_VICEPRESIDENTE: ROLE_VECINO
           
    access_control:
        - { path: ^/.*/root, roles: ROLE_ADMIN }
        - { path: ^/.*/adminfincas, roles: ROLE_ADMINFINCAS }
        - { path: ^/.*/propietario, roles: ROLE_VECINO }

    providers:
        administradores:
            memory:
                users:
                    root: { password: rootpass, roles: 'ROLE_ADMIN' }
        usuarios:
            entity: { class: EC\PrincipalBundle\Entity\Usuario, property: user }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        EC\PrincipalBundle\Entity\Usuario:
              algorithm:  sha512
              iterations: 10
              encode_as_base64: false