ec_adminfincas_homepage:
    pattern:  /
    defaults: { _controller: ECAdminFincasBundle:Default:index }
    
ec_adminfincas_alta_comunidad:
    pattern:  /alta/comunidad
    defaults: { _controller: ECAdminFincasBundle:Comunidad:alta_comunidad }

ec_adminfincas_listado_comunidades:
    pattern:  /listado/comunidades
    defaults: { _controller: ECAdminFincasBundle:Comunidad:listado_comunidades }
    
ec_adminfincas_listado_comunidades_pdf:
    pattern:  /listado/comunidades/pdf
    defaults: { _controller: ECAdminFincasBundle:Comunidad:listado_comunidades_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_listado_comunidades_csv:
    pattern: /listado/comunidades/csv
    defaults: { _controller: ECAdminFincasBundle:Comunidad:listado_comunidades_csv }
    
ec_adminfincas_comunidad_alta_propietario:
    pattern:  /comunidad/{cif}/alta/propietario
    defaults: { _controller: ECAdminFincasBundle:Propietario:alta_propietario }
    
ec_adminfincas_comunidad:
    pattern:  /comunidad/{cif}
    defaults: { _controller: ECAdminFincasBundle:Comunidad:comunidad }    
    
ec_adminfincas_comunidad_listado_propietarios:
    pattern:  /comunidad/{cif}/listado/propietarios
    defaults: { _controller: ECAdminFincasBundle:Propietario:comunidad_listado_propietarios }
    
ec_adminfincas_comunidad_listado_propietarios_pdf:
    pattern:  /comunidad/{cif}/listado/propietarios/pdf
    defaults: { _controller: ECAdminFincasBundle:Propietario:comunidad_listado_propietarios_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_propietarios_csv:
    pattern: /comunidad/{cif}/listado/propietarios/csv
    defaults: { _controller: ECAdminFincasBundle:Propietario:comunidad_listado_propietarios_csv }
    
ec_adminfincas_comunidad_eliminar_propietario:
    pattern:  /comunidad/{cif}/propietario/eliminar/{id}
    defaults: { _controller: ECAdminFincasBundle:Propietario:comunidad_eliminar_propietario } 
        
ec_adminfincas_comunidad_listado_bloques:
    pattern:  /comunidad/{cif}/listado/bloques
    defaults: { _controller: ECAdminFincasBundle:Bloque:comunidad_listado_bloques }
    
ec_adminfincas_comunidad_listado_bloques_pdf:
    pattern:  /comunidad/{cif}/listado/bloques/pdf
    defaults: { _controller: ECAdminFincasBundle:Bloque:comunidad_listado_bloques_pdf, _format: pdf }
    requirements:
      _format: pdf
      
ec_adminfincas_comunidad_listado_bloques_csv:
    pattern: /comunidad/{cif}/listado/bloques/csv
    defaults: { _controller: ECAdminFincasBundle:Bloque:comunidad_listado_bloques_csv }
    
ec_adminfincas_comunidad_alta_bloque:
    pattern:  /comunidad/{cif}/alta/bloque
    defaults: { _controller: ECAdminFincasBundle:Bloque:comunidad_alta_bloque }
    
ec_adminfincas_comunidad_editar:
    pattern:  /comunidad/{cif}/editar
    defaults: { _controller: ECAdminFincasBundle:Comunidad:editar_comunidad }
    
ec_adminfincas_comunidad_eliminar:
    pattern:  /comunidad/{cif}/eliminar
    defaults: { _controller: ECAdminFincasBundle:Comunidad:eliminar_comunidad }

ec_adminfincas_nombrar_presidente:
    pattern:  /comunidad/{cif}/nombrarpresidente/{id}
    defaults: { _controller: ECAdminFincasBundle:Propietario:nombrar_presidente }

ec_adminfincas_nombrar_vicepresidente:
    pattern:  /comunidad/{cif}/nombrarvicepresidente/{id}
    defaults: { _controller: ECAdminFincasBundle:Propietario:nombrar_vicepresidente }

ec_adminfincas_perfil:
    pattern:  /perfil
    defaults: { _controller: ECAdminFincasBundle:Default:modificacion_perfil }
    
ec_adminfincas_contraseña:
    pattern:  /contraseña
    defaults: { _controller: ECAdminFincasBundle:Default:modificacion_contraseña }