parameters:
#    ec_comunidad.example.class: EC\ComunidadBundle\Example

services:
#    ec_comunidad.example:
#        class: %ec_comunidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
